name: Build Docker Images

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:
    name: Caddy V2ray
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest V2ray Version
        id: v2ray
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: v2fly/v2ray-core
          excludes: "prerelease, draft"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            V2R_VERSION=${{ steps.v2ray.outputs.release }}
          push: true
          platforms: linux/arm64
          tags: anerg/v2ray:latest, anerg/v2ray:${{ steps.v2ray.outputs.release }}
